### ISSUE TITLE
The data link can't be opened.

### ISSUE THREAD

**Issue by pengxiand** [AIRI-Institute/GENA_LM#1]
Hi, what nice work, and thanks for your good work!

I want to use your pre-train model to fine-tune some other tasks but I can't open the data URL you put in the readme, and I would like to know the data format as input in your work, could you please help me with that?

**Comment by yurakuratov** [comment]
Hi! Thank you for your interest.

I guess that the problem is with Promoter Prediction downstream task. The correct link to get data for the Promoter Prediction downstream task is https://epd.epfl.ch/EPDnew_select.php. You should set `database` to `H. sapiens`, set `Restrict the selection to the following IDs` to `EPDnew ID` and press select. On the next page in `Sequence Extraction Tool (FASTA format)` you can choose region for extraction, .e.g., from -249 to 50.

Feel free to re-open this issue if it does not help.
