### ISSUE TITLE
Usage of sparse attention within GENA_LM

### ISSUE THREAD

**Issue by immanuelazn** [AIRI-Institute/GENA_LM#9]
Hi Yuri and Veniamin.

Thanks for sharing your work, I very much enjoyed reading about how you were able to extend context length much further than what can be typically used within DNABERT. 

I have a question though, regarding your choice of attention mechanism.  I understand that sparse attention has been a pivotal part in increasing context length for sequences.  However, I am wondering why sparse attention was utilized, rather than using Flash attention.  From what I understand with the current state of the art within NLP, there has been quite a massive shift towards usage of flash attention as the mechanism of decreasing training time and increasing context.

Thank you!

**Comment by yurakuratov** [comment]
Hi! Great question! 

Theoretically, the number of operations for full attention would always be higher than for sparse attention, because sparse attention removes full blocks of the attention matrix from the computation.

Flash Attention is a very efficient implementation of regular full attention, taking into account GPU architecture.

In our experiments, we chose sparse attention for historical reasons, there was no flash attention at the moment when we started our work.

Actually, these two approaches could be combined together, and sparse attention methods can benefit from flash attention. It would be nice to have the best of both worlds in one model! :)

**Comment by immanuelazn** [comment]
Interestingly enough, there's been some recent work doing exactly that (Sparse flash attention; https://doi.org/10.48550/arXiv.2306.01160).  Could be very promising in terms of reducing training time for future foundational genomic language models.  Let me know if I can help!
